import Navbar from '@/components/navbar'
import '@/styles/globals.css'

export const metadata = {
  title: 'GT3 - Generate Tab',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="bg-slate-900">
      <body>
        <Navbar />
        <main className="min-w-xs mx-auto flex max-w-screen-md flex-col items-center justify-center">
          {children}
        </main>
      </body>
    </html>
  )
}
